export const COLOURS ={
  white: '#ffffff',
  black: '#000000',
  green: '#00AC76',
  red: '#C04345',
  blue: '#0043F9',
  grey:'grey',
  backgroundLight: '#F0F0F3',
  backgroundMedium: '#B9B9B9',
  backgroundDark: '#777777',
}
export const Items =[
    {
        id:1,
        category: 'product',
        productName:'Blue half-slik Jamdani Saree',
        productPrice:1050,
        description:'Material Blue half silk Jamdani saree',
        isOff:true,
        offPercentage: 10,
        productImage: require('../database/images/products/girl-blue-01.jpg'),
        isAvailable:true,
        productImageList:[
            require('../database/images/products/blue-1.jpg'),
            require('../database/images/products/blue-2.jpeg'),
            require('../database/images/products/blue-3.jpg'),

        ]
        
    },
    {
        id: 2,
        category: 'product',
        productName: 'Black Jamdani Saree',
        productPrice: 1499,
        description:'Material Black half silk ',
        isOff: false,
        productImage: require('../database/images/products/black-girl.jpg'),
        productImageList: [
          require('../database/images/products/black-01.jpg'),
          require('../database/images/products/black-02.jpeg'),
          require('../database/images/products/black-03.jpg'),
        ],
      },
      {
        id: 3,
        category: 'accessory',
        productName: 'HD Foundation',
        productPrice: 499,
        description:'Ultra-glow Full Make-up HD Foundation',
        isOff:true,  
        offPercentage:18,
        productImage: require('../database/images/accessories/f-f.jpg'),
        isAvailable:true,
        productImageList: [
          require('../database/images/accessories/f-1.jpg'),
          require('../database/images/accessories/f-2.jpg'),
          require('../database/images/accessories/f-3.jpg'),
        ],
      },
      {
        id: 4,
        category: 'accessory',
        productName: 'Lakme Kajal',
        productPrice: 199,
        description:'Lakme 24hr long lasting Kajal.',
        isOff:false,
        productImage: require('../database/images/accessories/L-F-f.jpg'),
       isAvailable:true,
        productImageList: [
          require('../database/images/accessories/L-f.jpg'),
          require('../database/images/accessories/L-02.jpg'),
          require('../database/images/accessories/L-03.jpg'),
        ],
      },
      {
        id: 5,
        category: 'accessory',
        productName: 'Floral Bracelet',
        productPrice: 149,
       isOff: false,
       // offPercentage: 18,  
        productImage: require('../database/images/accessories/bracelet1.jpg'),
        isAvailable:false,
        productImageList: [
          require('../database/images/accessories/bracelet2.jpg'),
          require('../database/images/accessories/bracelet3.jpg'),
          require('../database/images/accessories/bracelet_4.jpg'),
        ],
      },
      {
        id: 6,
        category: 'accessory',
        productName: 'Necklace with Pendant',
        productPrice: 1299,
        productImage: require('../database/images/accessories/neck1.jpg'),
        isAvailable:true,
        productImageList: [
          require('../database/images/accessories/neck2.jpg'),
          require('../database/images/accessories/neck3.jpg'),
          require('../database/images/accessories/neck4.jpg'),
        ],
      },
]